server:
  port: 8000
spring:
  datasource:
    username: auction
    password: mtwYSZfeFCydX46A
    url: jdbc:mysql://system.valinaa-wei.tech:3306/auction?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: system.valinaa-wei.tech
    port: 6379
    password: valina
    lettuce:
      pool:
        max-active: 15
        max-idle: 10
        min-idle: 2
        time-between-eviction-runs: 1000
  cache:
    type: redis

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

springdoc:
  packages-to-scan: cn.valinaa.auction.controller
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    enabled: true

knife4j:
  enable: true
  setting:
    language: zh_cn
#logging:
#  config: classpath:log4j2.xml
